/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learn;

import javax.swing.JOptionPane;
import java.util.Random;
import java.lang.reflect.Method;
import javax.swing.DefaultListModel;
/**
 *
 * @author cristiano
 */
public class SortComparationGUI extends javax.swing.JFrame {

    /**
     * Creates new form SortComparationGUI
     */
    public SortComparationGUI() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Inserisci la dimensione dell'array e scegli tipo di sort");
        modello = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnCalcola = new javax.swing.JButton();
        ComboSort = new javax.swing.JComboBox<>();
        txtNumberOfElement = new javax.swing.JTextField();
        lblElement = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblValTime = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListElementiDisordinati = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListElementiOrdinati = new javax.swing.JList();
        lblElemDis = new javax.swing.JLabel();
        lblElemOrd = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));

        btnCalcola.setText("Ordina");
        btnCalcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcolaActionPerformed(evt);
            }
        });

        ComboSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BubbleSort", "QuickSort", "MergeSort", "BitonicSort", "InsertionSort", "SelectionSort", "ShakerSort", "CountingSort", "RedixSort" }));
        ComboSort.setToolTipText("Choose sort method");
        ComboSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSortActionPerformed(evt);
            }
        });

        txtNumberOfElement.setText("0");
        txtNumberOfElement.setToolTipText("Array dimension");
        txtNumberOfElement.setName(""); // NOI18N
        txtNumberOfElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfElementActionPerformed(evt);
            }
        });

        lblElement.setText("Number of elements");

        lblTime.setText("Timer");

        lblValTime.setText("0 sec");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListElementiDisordinati);

        jScrollPane2.setViewportView(ListElementiOrdinati);

        lblElemDis.setText("Elementi Disordinati");

        lblElemOrd.setText("Elementi Ordinati");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumberOfElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblElement))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTime)
                                .addGap(18, 18, 18)
                                .addComponent(lblValTime)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblElemDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCalcola, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblElemOrd, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumberOfElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblElement))
                        .addGap(49, 49, 49)
                        .addComponent(ComboSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime)
                            .addComponent(lblValTime)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblElemDis)
                            .addComponent(lblElemOrd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnCalcola))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txtNumberOfElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfElementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfElementActionPerformed

    private void ComboSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSortActionPerformed

    private void btnCalcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcolaActionPerformed
       int indice;
        try{
             indice = Integer.parseInt(txtNumberOfElement.getText());
            if(indice < 1)            
                JOptionPane.showMessageDialog(null, "Dimensione vettore non possibile", "Errore", JOptionPane.WARNING_MESSAGE);  
            else
                v = new int[indice];
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Errore", JOptionPane.WARNING_MESSAGE);
        } 
        if(v.length > 0)//se è andato tutto a buon fine
        {            
            Random n = new Random();
            for (int i = 0; i < v.length; i++) {
                v[i] = n.nextInt(100);
                modello.addElement(v[i]);
            }            
            ListElementiDisordinati.setModel(modello);
            modello = new DefaultListModel();//per poter inserire poi gli elementi ordinati
            
            double inizio = 0;
            boolean errore = false;
            String mexErrore = null;
            
            try{
            //REFLECTION            
            inizio = System.currentTimeMillis(); 
            String nomeClasse = (ComboSort.getSelectedItem()).toString();
            Class classe = Class.forName("learn." + nomeClasse);
            Method metodo = classe.getMethod("Sort", int[].class);
            metodo.invoke(classe.newInstance(), (Object)v);
            }
            catch(Exception e){
                mexErrore = e.getMessage();
                errore = true;
            }
            
            double fine = System.currentTimeMillis();
            timer = (fine -inizio)/1000;
            if(!errore){//se è tutto corretto metto i dati nella list box altrimenti nulla
            lblValTime.setText("= " + timer + " sec");
            for (int i = 0; i < v.length; i++) {
                   modello.addElement(v[i]);
                }
            ListElementiOrdinati.setModel(modello);
            }
            else
                JOptionPane.showMessageDialog(null, mexErrore,"Errore",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcolaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        v = null;
        lblValTime.setText("= 0 sec");
        txtNumberOfElement.setText("0");
        ComboSort.setSelectedItem("BubbleSort");
        modello = new DefaultListModel();
        ListElementiDisordinati.setModel(modello);
        ListElementiOrdinati.setModel(modello);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortComparationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortComparationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortComparationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortComparationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortComparationGUI().setVisible(true);
            }
        });
    }
//variabili dichiarate da me
    private int[] v;
    private double timer;
    DefaultListModel modello;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboSort;
    private javax.swing.JList ListElementiDisordinati;
    private javax.swing.JList ListElementiOrdinati;
    private javax.swing.JButton btnCalcola;
    private javax.swing.JButton btnReset;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblElemDis;
    private javax.swing.JLabel lblElemOrd;
    private javax.swing.JLabel lblElement;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblValTime;
    private javax.swing.JTextField txtNumberOfElement;
    // End of variables declaration//GEN-END:variables
}
